# Generated by Django 5.2.11 on 2026-05-25

import django.db.models.deletion
from django.db import migrations, models


PROJECTS = [
    ("Parent Fuelling IKF",
     "Your support keeps every IKF opportunity alive for the next player who needs it.",
     "/parent-fuelling-ikf", 10),
    ("Naari Shakti",
     "Empowering girls across India through football, mentorship, and structured opportunities.",
     "/naari_shakti", 20),
    ("Field of Dreams - Future Champion",
     "Player development plus life skills for young athletes of all ages.",
     "/field_of_dreams", 30),
    ("Field of Dreams - Maidaan Ki Raani",
     "Female player development combined with life-skills training.",
     "/field_of_dreams", 40),
    ("Field of Dreams - Books & Boots",
     "Player development plus literacy support for 11th & 12th standard students.",
     "/field_of_dreams", 50),
    ("IKF Trials",
     "Non-profit, data-driven talent hunts for players aged 10–17 across India.",
     "/IkfTrials", 60),
    ("i-Care By Invictus",
     "A student-led movement from O.P. Jindal Global University transforming Indian football.",
     "https://indiakhelofootball.com/invictusxOPJindal", 70),
    ("Anaya's Goal",
     "Raising funds for football equipment for young girls who dream of playing.",
     "/Anaya-Goal", 80),
]


def seed_projects(apps, schema_editor):
    DonateProject = apps.get_model("main", "DonateProject")
    for name, desc, url, order in PROJECTS:
        DonateProject.objects.get_or_create(
            name=name,
            defaults={
                "description": desc,
                "read_more_url": url,
                "display_order": order,
                "is_active": True,
            },
        )


def unseed_projects(apps, schema_editor):
    DonateProject = apps.get_model("main", "DonateProject")
    DonateProject.objects.filter(name__in=[p[0] for p in PROJECTS]).delete()


def table_exists(schema_editor, table_name):
    return table_name in schema_editor.connection.introspection.table_names()


def column_exists(schema_editor, table_name, column_name):
    if not table_exists(schema_editor, table_name):
        return False
    with schema_editor.connection.cursor() as cursor:
        existing_columns = schema_editor.connection.introspection.get_table_description(cursor, table_name)
    return any(column.name == column_name for column in existing_columns)


def create_donateproject_if_missing(apps, schema_editor):
    from main.models import DonateProject
    if table_exists(schema_editor, DonateProject._meta.db_table):
        return
    schema_editor.create_model(DonateProject)


def delete_donateproject_if_present(apps, schema_editor):
    from main.models import DonateProject
    if table_exists(schema_editor, DonateProject._meta.db_table):
        schema_editor.delete_model(DonateProject)


def create_donatesettings_if_missing(apps, schema_editor):
    from main.models import DonateSettings
    if table_exists(schema_editor, DonateSettings._meta.db_table):
        return
    schema_editor.create_model(DonateSettings)


def delete_donatesettings_if_present(apps, schema_editor):
    from main.models import DonateSettings
    if table_exists(schema_editor, DonateSettings._meta.db_table):
        schema_editor.delete_model(DonateSettings)


def add_donation_project_fk_if_missing(apps, schema_editor):
    from main.models import Donation
    if column_exists(schema_editor, Donation._meta.db_table, "project_id"):
        return
    field = models.ForeignKey(
        blank=True,
        help_text="Auto-linked from the donation purpose string at save time.",
        null=True,
        on_delete=django.db.models.deletion.SET_NULL,
        related_name="donations",
        to="main.donateproject",
    )
    field.set_attributes_from_name("project")
    schema_editor.add_field(Donation, field)


def remove_donation_project_fk_if_present(apps, schema_editor):
    from main.models import Donation
    if not column_exists(schema_editor, Donation._meta.db_table, "project_id"):
        return
    field = Donation._meta.get_field("project")
    schema_editor.remove_field(Donation, field)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0087_offlinedonationclaim"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_donateproject_if_missing, delete_donateproject_if_present),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="DonateProject",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("name", models.CharField(help_text="Project name shown as the card title.", max_length=200)),
                        ("description", models.CharField(help_text="One-line description shown under the title on the donate page.", max_length=300)),
                        ("read_more_url", models.CharField(blank=True, help_text="Optional fallback. Used as 'Know more' link ONLY when no detail-page content is filled.", max_length=500)),
                        ("display_order", models.PositiveIntegerField(db_index=True, default=100, help_text="Lower numbers appear first.")),
                        ("is_active", models.BooleanField(db_index=True, default=True, help_text="Uncheck to hide this project from the donate page.")),
                        ("razorpay_enabled", models.BooleanField(default=True, help_text="Show Razorpay as a payment option for this project.")),
                        ("upi_enabled", models.BooleanField(default=True, help_text="Show UPI as a payment option for this project.")),
                        ("bank_enabled", models.BooleanField(default=True, help_text="Show Bank Transfer as a payment option for this project.")),
                        ("preset_amounts", models.CharField(default="500,1000,5000,10000", help_text="Comma-separated INR amounts shown as quick-select buttons. e.g. 500,1000,5000,10000", max_length=200)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "Donate Page Project",
                        "verbose_name_plural": "Donate Page Projects",
                        "ordering": ["display_order", "id"],
                    },
                ),
            ],
        ),
        migrations.RunPython(seed_projects, unseed_projects),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_donatesettings_if_missing, delete_donatesettings_if_present),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="DonateSettings",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("reg_80g", models.CharField(default="AAICK4512EF20214", max_length=100)),
                        ("csr_number", models.CharField(default="CSR00022415", max_length=100)),
                        ("upi_id", models.CharField(default="khelofootball.123@idfcbank", max_length=100)),
                        ("upi_qr_image", models.ImageField(blank=True, help_text="UPI QR shown when donor picks UPI.", null=True, upload_to="donateus")),
                        ("bank_account_name", models.CharField(default="KHELO FOOTBALL ECOSYSTEM DEVELOPMENT FEDERATION", max_length=200)),
                        ("bank_account_number", models.CharField(default="10064068880", max_length=50)),
                        ("bank_ifsc", models.CharField(default="IDFB0040162", max_length=20)),
                        ("bank_swift", models.CharField(default="IDFBINBBMUM", max_length=20)),
                        ("bank_name", models.CharField(default="IDFC FIRST", max_length=100)),
                        ("bank_branch", models.CharField(default="Thane - Hiranandani Estate", max_length=200)),
                        ("whatsapp_number", models.CharField(default="+91 88501 19762", max_length=30)),
                        ("donate_email", models.EmailField(default="donate@indiakhelofootball.com", max_length=254)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "Donate Page Settings",
                        "verbose_name_plural": "Donate Page Settings",
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_donation_project_fk_if_missing, remove_donation_project_fk_if_present),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="donation",
                    name="project",
                    field=models.ForeignKey(blank=True, help_text="Auto-linked from the donation purpose string at save time.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="donations", to="main.donateproject"),
                ),
            ],
        ),
    ]
