# Generated by Django 5.2.11 on 2026-05-25

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def column_exists(schema_editor, table_name, column_name):
    with schema_editor.connection.cursor() as cursor:
        existing_columns = schema_editor.connection.introspection.get_table_description(cursor, table_name)
    return any(column.name == column_name for column in existing_columns)


def table_exists(schema_editor, table_name):
    return table_name in schema_editor.connection.introspection.table_names()


def add_detail_banner_if_missing(apps, schema_editor):
    DonateProject = apps.get_model("main", "DonateProject")
    if column_exists(schema_editor, DonateProject._meta.db_table, "detail_banner"):
        return
    field = models.ImageField(
        blank=True,
        help_text="Detail page banner (right side of the hero). Recommended size: 1200 x 900 px (4:3 aspect ratio). Max file size 2 MB. JPG/PNG/WebP.",
        null=True,
        upload_to="donate/projects/",
    )
    field.set_attributes_from_name("detail_banner")
    schema_editor.add_field(DonateProject, field)


def add_detail_intro_if_missing(apps, schema_editor):
    DonateProject = apps.get_model("main", "DonateProject")
    if column_exists(schema_editor, DonateProject._meta.db_table, "detail_intro"):
        return
    field = models.TextField(
        blank=True,
        default="",
        help_text="Longer introduction shown next to the banner on the detail page. Falls back to the short description if blank.",
    )
    field.set_attributes_from_name("detail_intro")
    schema_editor.add_field(DonateProject, field)


def add_slug_if_missing(apps, schema_editor):
    DonateProject = apps.get_model("main", "DonateProject")
    if column_exists(schema_editor, DonateProject._meta.db_table, "slug"):
        return
    field = models.SlugField(
        blank=True,
        default="",
        help_text="Auto-generated from the project name. Used in the URL: /donate/<slug>/. Leave blank to auto-fill.",
        max_length=220,
    )
    field.set_attributes_from_name("slug")
    schema_editor.add_field(DonateProject, field)


def create_section_table_if_missing(apps, schema_editor):
    from main.models import DonateProjectSection
    if table_exists(schema_editor, DonateProjectSection._meta.db_table):
        return
    schema_editor.create_model(DonateProjectSection)


def drop_section_table_if_present(apps, schema_editor):
    from main.models import DonateProjectSection
    if table_exists(schema_editor, DonateProjectSection._meta.db_table):
        schema_editor.delete_model(DonateProjectSection)


def backfill_slugs(apps, schema_editor):
    DonateProject = apps.get_model("main", "DonateProject")
    used = set()
    for proj in DonateProject.objects.all().order_by("id"):
        if getattr(proj, "slug", ""):
            used.add(proj.slug)
            continue
        base = slugify(proj.name or "")[:200] or f"project-{proj.pk}"
        candidate = base
        i = 2
        while candidate in used or DonateProject.objects.filter(slug=candidate).exclude(pk=proj.pk).exists():
            candidate = f"{base}-{i}"
            i += 1
        used.add(candidate)
        proj.slug = candidate
        proj.save(update_fields=["slug"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0076_donation_project"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_detail_banner_if_missing, noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="donateproject",
                    name="detail_banner",
                    field=models.ImageField(blank=True, help_text="Detail page banner (right side of the hero). Recommended size: 1200 x 900 px (4:3 aspect ratio). Max file size 2 MB. JPG/PNG/WebP.", null=True, upload_to="donate/projects/"),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_detail_intro_if_missing, noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="donateproject",
                    name="detail_intro",
                    field=models.TextField(blank=True, help_text="Longer introduction shown next to the banner on the detail page. Falls back to the short description if blank."),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_slug_if_missing, noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="donateproject",
                    name="slug",
                    field=models.SlugField(blank=True, default="", help_text="Auto-generated from the project name. Used in the URL: /donate/<slug>/. Leave blank to auto-fill.", max_length=220),
                    preserve_default=False,
                ),
            ],
        ),
        migrations.RunPython(backfill_slugs, noop),
        migrations.AlterField(
            model_name="donateproject",
            name="slug",
            field=models.SlugField(blank=True, help_text="Auto-generated from the project name. Used in the URL: /donate/<slug>/. Leave blank to auto-fill.", max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name="donateproject",
            name="description",
            field=models.CharField(help_text="One-line description shown under the title on the donate page.", max_length=300),
        ),
        migrations.AlterField(
            model_name="donateproject",
            name="read_more_url",
            field=models.CharField(blank=True, help_text="Optional fallback. Used as 'Know more' link ONLY when no detail-page content is filled.", max_length=500),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_section_table_if_missing, drop_section_table_if_present),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="DonateProjectSection",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("heading", models.CharField(max_length=200)),
                        ("content", models.TextField(help_text="Body text shown under the heading. Plain text or simple HTML.")),
                        ("image", models.ImageField(blank=True, help_text="Optional. When present, image sits beside the text. When blank, text spans full width. Recommended size: 1000 x 750 px (4:3 aspect ratio). Max file size 2 MB. JPG/PNG/WebP.", null=True, upload_to="donate/projects/sections/")),
                        ("display_order", models.PositiveIntegerField(db_index=True, default=100, help_text="Lower numbers appear first.")),
                        ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="main.donateproject")),
                    ],
                    options={
                        "verbose_name": "Donate Project Section",
                        "verbose_name_plural": "Donate Project Sections",
                        "ordering": ["display_order", "id"],
                    },
                ),
            ],
        ),
    ]
