# Generated by Django 5.2.11 on 2026-05-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0077_donateproject_detail_banner_and_more"),
        ("main", "0087_offlinedonationclaim"),
    ]

    operations = []
