SCOUT_LETTER = {
    "title": "IKF Certified Level 2 Scouts",
    "salutation": "Dear Partners,",
    "body": [
        "At India Khelo Football (IKF), our mission has always been clear — to build a transparent, reliable and scalable scouting ecosystem for Indian football. Over the last few years, we have invested deeply in training, certifying and mentoring scouts across the country through our IKF CFSA Level 1 (Talent Identification) and IKF CFSA Level 2 (Positional Scouting) programs.",
        "Every scout featured here has successfully completed both certifications and has also worked hands-on in IKF Trials, Zonals, National Finals, grassroots tournaments and live match scouting assignments. They represent a growing community of trained professionals who understand modern scouting, objective evaluation, and the realities of Indian football.",
        "This initiative is our way of giving back to the ecosystem. We want clubs and academies like yours to have access to trained, credible and field-tested scouts — without any cost, expectation or obligation from IKF. Our only goal is to strengthen the scouting pipeline and ensure that more players across India are seen, assessed and given the right opportunities.",
        "I invite you to go through the profiles and engage with these scouts directly — whether for full-time roles, seasonal requirements, or project-based assignments. If you wish to coordinate with multiple scouts across regions, IKF will be happy to support you as a central coordination body.",
    ],
    "closing": "Together, we can build a stronger, more efficient and more inclusive talent identification system for Indian football.",
    "signature": ["Warm regards,", "Phani Bhushan", "Director, India Khelo Football (IKF)"],
}

SCOUT_DETAILS_CONTEXT = {
    "heading": "Why is IKF sharing it's scouts details ?",
    "intro": "IKF is committed to enhancing the football talent ecosystem in India. These scout details have been shared with clubs so that they can hire certified and experienced scouts full time and part time.",
    "objectives": [
        {
            "title": "Build Capacity in Scouting Across India",
            "text": "India needs more trained, dependable, and regionally diverse scouts. All scouts featured here have completed IKF CFSA Level 1 and Level 2 certifications, gained experience in IKF Trials and real match situations, and demonstrated professionalism, consistency, and technical expertise.",
        },
        {
            "title": "Support Clubs and Academies With Ready to Deploy Scouting Resources",
            "text": "Clubs often face challenges in finding credible scouts adept at structured evaluations. This page addresses that need by providing immediate access to trained scouts across various states and age groups.",
        },
        {
            "title": "Offer This Service at No Cost or Expectation",
            "text": "IKF does not impose any fees, commissions, or placement costs. This initiative is purely aimed at building the ecosystem to help clubs enhance their scouting departments.",
        },
    ],
    "usage": [
        "Hire scouts full time based on your vacancies.",
        "Engage scouts on a project basis for tournaments, trials, league scouting, academy evaluations, or short term projects.",
        "Use IKF as a coordination body for multi city or multi state scouting assignments.",
    ],
}

SCOUT_PROFILES = [
    {
        "name": "Kaushik Chatterjee",
        "slug": "kaushik-chatterjee",
        "photo": "Kaushik.jpeg",
        "city": "Kolkata",
        "state": "West Bengal",
        "age_date_of_birth": "45 Years (08/07/1981)",
        "languages": "Bengali, English, Hindi",
        "willingness_to_travel": "Travel for assignment",
        "phone": "9831446612",
        "email": "kc08071981@gmail.com",
        "experience": "1.5 years",
        "level1_completion_date": "18/05/2025 (IKF-CFSA-L1-B2504)",
        "level2_completion_date": "22/03/2026 (IKF-CFSA-L1-B2504)",
        "types": "Live match scouting, tournament scouting, video scouting, grassroots scouting",
        "competitions": "Subroto Cup 2025, IKF City Trials, IKF National Trial 2025",
        "age_groups": "U13, U15, U17",
        "regions": "Eastern Region, primarily West Bengal",
        "players_assessed": "750+",
        "shortlisted": "",
        "events": "Represented Zinc Football Academy during IKF National Trials 2025",
        "strengths": "Player evaluation and profiling, positional analysis, live match scouting, video scouting, report writing, grading and recommendation, Excel, Google Sheets, basic video tools, Indian grassroots pathways.",
        "playing": "Milan Samity (CFL 3rd division). District level midfielder / winger with 7 years active experience.",
        "achievements": "Identified 4 players in IKF City Trials who later progressed to IKF National Trials. Assigned to represent Zinc Football Academy as a scout during IKF National Trials 2025 by mentor. Consistently aligned scouting recommendations with trial outcomes and coach feedback. Actively supports and guides junior scouts in the Eastern Region during assignments.",
        "certification": "IKF-CFSA-L1-B2504",
        "featured": True,
    },
    {
        "name": "Vaibhav Keshav Wable",
        "slug": "vaibhav-keshav-wable",
        "photo": "Vaibhav.jpeg",
        "city": "Pune",
        "state": "Maharashtra",
        "age_date_of_birth": "28 Years (01/08/1997)",
        "languages": "Marathi, Hindi, English",
        "willingness_to_travel": "Yes",
        "phone": "7885993681",
        "email": "Vaibhavwable1997@gmail.com",
        "experience": "1.5 years",
        "level1_completion_date": "20/03/2025 (IKF-CFSA-L1-B2503)",
        "level2_completion_date": "20/12/2025 (IKF-CFSA-L1-B2503)",
        "types": "On-ground scouting",
        "competitions": "",
        "age_groups": "U17",
        "regions": "Pune",
        "players_assessed": "500+",
        "shortlisted": "12-20",
        "events": "Scouting for IKF",
        "strengths": "Youth scouting, tactical observation, player evaluation, positional analysis, live and video match scouting, report writing and grading.",
        "playing": "Stallions Pune FC. State level CDM.",
        "achievements": "",
        "certification": "IKF-CFSA-L1-B2503",
        "featured": True,
    },
    {
        "name": "Naga Sai Kalyan Koneru",
        "slug": "naga-sai-kalyan-koneru",
        "photo": "Naga Sai .jpeg",
        "city": "Hyderabad",
        "state": "Telangana",
        "age_date_of_birth": "34 Years (11/05/1991)",
        "languages": "English, Telugu, Hindi, Tamil",
        "willingness_to_travel": "Yes",
        "phone": "9704639392",
        "email": "kalyan.stands@gmail.com",
        "experience": "2 years",
        "level1_completion_date": "12/02/2025 (IKF-CFSA-L1-B2501)",
        "level2_completion_date": "12/03/2026 (IKF-CFSA-L1-B2501)",
        "types": "Live matches, tournaments, video, grassroots",
        "competitions": "Live Matches: IKF Season 4 and IKF Season 5. Grassroot Tournaments: Slum Soccer 2026 Telangana State Trials. Video: IKF East Zonals 2025, Scout Lab V3 2026.",
        "age_groups": "U13, U15, U17 and senior level",
        "regions": "Visakhapatnam, Rajahmundry, Vijayawada, Guntur, Jangareddygudem, Mylavaram, Hindupur, Anantapur, Medak, Warangal, Shamirpet, Tirupati, Bangalore",
        "players_assessed": "2,200 approx",
        "shortlisted": "225",
        "events": "IKF, Slum Soccer, Scout Lab",
        "strengths": "Player evaluation, positional analysis, KPI tracking for recruitment, match scouting (live + video), report writing and grading. Tools: Excel, Sheets, In-Play Online, Nacsport Pro/Scout, My-Game Plan, Python, Tableau. Specialised in positional scouting, youth scouting, tactical observation, video analysis basics, team internal evaluations, network building with grassroot academies and state federations.",
        "playing": "",
        "achievements": "Players identified who progressed to higher trials: 10+. High accuracy in player grading and regional scouting consistency.",
        "certification": "IKF-CFSA-L1-B2501",
        "featured": True,
    },
    {
        "name": "Rohit Dsouza",
        "slug": "rohit-dsouza",
        "photo": "Rohit.jpeg",
        "city": "Mumbai",
        "state": "Maharashtra",
        "age_date_of_birth": "39 Years (21/01/1987)",
        "languages": "English, Hindi, Marathi, Konkani",
        "willingness_to_travel": "Depends on assignment",
        "phone": "9833236364",
        "email": "rohitdsouza7@gmail.com",
        "experience": "6 years",
        "level1_completion_date": "12/04/2024 (IKFL1B240405)",
        "level2_completion_date": "28/02/2026 (IKFL1B240405)",
        "types": "Live match, tournament, grassroots, academy",
        "competitions": "",
        "age_groups": "U12, U14, U16 and senior level",
        "regions": "Mumbai",
        "players_assessed": "2000+",
        "shortlisted": "",
        "events": "IKF, own club and academy, other MFA clubs",
        "strengths": "Positional scouting, youth scouting, tactical observation, video analysis basics, live and video match scouting, report writing and grading, Excel/Sheets/video tools.",
        "playing": "Friends United MFA club and Black Ants FC (futsal). Regional / district level defender and midfielder, active since 2014.",
        "achievements": "Players identified who progressed to higher trials. Recognised by clubs/academies/mentors. High accuracy in player grading.",
        "certification": "IKFL1B240405",
        "featured": True,
    },
    {
        "name": "Satish Narayanan Iyer",
        "slug": "satish-narayanan-iyer",
        "photo": "Satish.jpeg",
        "city": "Mumbai / Pune",
        "state": "Maharashtra",
        "age_date_of_birth": "59 Years (19/01/1967)",
        "languages": "Tamil, English, Hindi, Marathi, Malayalam, Telugu",
        "willingness_to_travel": "Yes",
        "phone": "9884808134",
        "email": "adityajaya0@gmail.com",
        "experience": "2 years",
        "level1_completion_date": "14/02/2025 (IKFL1B250101)",
        "level2_completion_date": "21/11/2025 (IKFL1B250101)",
        "types": "Live match, tournament, video, grassroots, academy",
        "competitions": "Grassroots and local tournaments in Mumbai",
        "age_groups": "U16",
        "regions": "Mumbai / Poona",
        "players_assessed": "1000+",
        "shortlisted": "10",
        "events": "",
        "strengths": "Youth scouting, tactical observation, player evaluation, positional analysis, match scouting, report writing, Excel/Sheets/video tools, Indian football ecosystem understanding.",
        "playing": "Falcon Sports Club First Division Team in PDFA. District level goalkeeper, full back, striker and midfielder with 30 years active experience.",
        "achievements": "",
        "certification": "IKFL1B250101",
        "featured": False,
    },
    {
        "name": "Arnab Chakraborty",
        "slug": "arnab-chakraborty",
        "photo": "arnab.jpeg",
        "city": "North 24 Parganas",
        "state": "West Bengal",
        "age_date_of_birth": "34 Years (10/05/1991)",
        "languages": "Bengali, English, Hindi",
        "willingness_to_travel": "Yes",
        "phone": "8100208430",
        "email": "arnab1991@live.com",
        "experience": "1 year",
        "level1_completion_date": "07/03/2025 (IKFL1B250205)",
        "level2_completion_date": "07/05/2025 (IKFL1B250205)",
        "types": "Live match, grassroots trials, video analysis",
        "competitions": "On Ground: IKF S5 and S6 City Trials, IKF S5 East Zonal Finals (Ranchi). Video Scouting: IKF S5 North Goa Trials, RFYS Delhi Championship 24-25, AIFF Junior and Sub-Junior Leagues 24-25, Subroto Cup U-15 2025.",
        "age_groups": "U13, U15, U17",
        "regions": "West Bengal",
        "players_assessed": "700+",
        "shortlisted": "110+",
        "events": "IKF",
        "strengths": "Youth talent identification, positional analysis, video-based performance grading, objective KPI evaluation, advanced Mi-Tas and My First Kick app usage, deep Indian football pyramid knowledge (ISL, I-League, AIFF youth structures), written player evaluations.",
        "playing": "Casual playing experience with a deep focus on technical theory.",
        "achievements": "Successfully identified 14 players during the IKF S5 Central Kolkata trials who progressed to the East Zonal Finals. Maintained consistent grading standards across 600+ player assessments. Entrusted as a recurring scout for the West Bengal region (Kolkata and Budge Budge trials). Voluntarily completed international certifications: PFSA Level 1 (Talent ID), FA Introduction to Talent ID and FA EE Playmaker.",
        "certification": "IKFL1B250205",
        "featured": True,
    },
    {
        "name": "Preston Anthony Dsouza",
        "slug": "preston-anthony-dsouza",
        "photo": "Preston.jpeg",
        "city": "Pune",
        "state": "Maharashtra",
        "age_date_of_birth": "30 Years (18/03/1996)",
        "languages": "English, Hindi, Konkani",
        "willingness_to_travel": "Yes",
        "phone": "8698537787",
        "email": "prestondsouza07@gmail.com",
        "experience": "2 years",
        "level1_completion_date": "21/02/2025 (IKFL1B250203)",
        "level2_completion_date": "21/11/2025 (IKFL1B250203)",
        "types": "Live matches, tournaments, video scouting, IKF trials, academy training observation",
        "competitions": "Poona District PDFA League, GOA Super Cup, academy-level competitions",
        "age_groups": "U10 - U18",
        "regions": "Pune, PCMC, Goa, Nagpur, Sambhaji Nagar (Aurangabad), Mumbai and nearby districts",
        "players_assessed": "1000+",
        "shortlisted": "80+",
        "events": "IKF Zonals, IKF Final",
        "strengths": "Youth scouting, player potential identification, positional basics, grassroots development, live match scouting, Excel, Google Sheets and academy system building.",
        "playing": "Sai Football Academy, Satara Hanuman Mandal, Mathew Football Academy. State league, district level, PDFA and local competitive level CDM / midfielder. Active 2014-2019 and 2023-2026.",
        "achievements": "Strong player evaluation at grassroots level. Developed multiple players into competitive-level squads. Built and managed the structured academy system FC Panthers. Recognised within local football circuits for youth development.",
        "certification": "IKFL1B250203",
        "featured": False,
    },
    {
        "name": "Suheil Daryanani",
        "slug": "suheil-daryanani",
        "photo": "Suheil.jpeg",
        "city": "Bangalore",
        "state": "Karnataka",
        "age_date_of_birth": "31 Years (25/10/1994)",
        "languages": "English, Hindi, Kannada",
        "willingness_to_travel": "Travel on assignments",
        "phone": "9740469473",
        "email": "suheildeepak94@gmail.com",
        "experience": "1 year",
        "level1_completion_date": "21/03/2025 (IKFL1B250204)",
        "level2_completion_date": "12/04/2026 (IKFL1B250204)",
        "types": "Live match, tournament, video, grassroots",
        "competitions": "AIFF Youth League, Subroto Cup",
        "age_groups": "U13, U15, U17",
        "regions": "Karnataka and Tamil Nadu",
        "players_assessed": "550+",
        "shortlisted": "90+",
        "events": "One Football Championship (Blue Cubs League in Bangalore)",
        "strengths": "Youth scouting and tactical observation, player evaluation, positional analysis, match scouting (live + video), report writing and grading, Excel/Sheets/video tools.",
        "playing": "Not applicable.",
        "achievements": "",
        "certification": "IKFL1B250204",
        "featured": False,
    },
    {
        "name": "Avro Mukerji",
        "slug": "avro-mukerji",
        "photo": "Avro.jpeg",
        "city": "Gurugram",
        "state": "Haryana",
        "age_date_of_birth": "45 Years (26/07/1980)",
        "languages": "English, Bengali, Hindi",
        "willingness_to_travel": "Yes",
        "phone": "9167142325",
        "email": "AVROMUKERJI@YAHOO.COM",
        "experience": "7 years",
        "level1_completion_date": "07/05/2025 (IKFL1B250105)",
        "level2_completion_date": "21/11/2025 (IKFL1B250105)",
        "types": "Live match, tournament, video, grassroots, academy",
        "competitions": "Subroto Cup",
        "age_groups": "U11, U13, U15, U17, Women's matches",
        "regions": "North",
        "players_assessed": "2500+",
        "shortlisted": "20-25",
        "events": "Scouted on behalf of IKF",
        "strengths": "Positional scouting, youth scouting, video analysis, Excel sheets, player evaluation, match scouting (live + video), report writing and grading, Indian football ecosystem.",
        "playing": "School and university. District level central midfielder (2000-2003).",
        "achievements": "Players identified who progressed to higher trials. Recognised by clubs and mentors. High accuracy in player grading.",
        "certification": "IKFL1B250105",
        "featured": False,
    },
    {
        "name": "Vishnu Teja Edara",
        "slug": "vishnu-teja-edara",
        "photo": "Vishnu.jpeg",
        "city": "Hyderabad",
        "state": "Telangana",
        "age_date_of_birth": "35 Years (12/03/1991)",
        "languages": "English, Bengali, Hindi",
        "willingness_to_travel": "Travel on assignments",
        "phone": "8655004448",
        "email": "vishnuteja312@gmail.com",
        "experience": "4 years",
        "level1_completion_date": "27/06/2024 (IKFL1B240506)",
        "level2_completion_date": "21/11/2025 (IKFL1B240506)",
        "types": "Live match, grassroots academy, state leagues, video",
        "competitions": "IKF trials, Telangana C Division",
        "age_groups": "U11, U13, U15, U17 and senior level",
        "regions": "Telangana, Andhra Pradesh",
        "players_assessed": "1000+",
        "shortlisted": "60",
        "events": "IKF, Bolarum Sporting Club, SGF, APFA 32 Stars",
        "strengths": "Positional scouting, youth scouting, tactical observation, video analysis, database management, data and video analysis tools, Indian and global football ecosystem understanding.",
        "playing": "Amateur level.",
        "achievements": "Helped players from Andhra and Telangana progress to the national trials of IKF. Analysis of Telangana teams who finished in the Top 4 at the Slum Soccer National Tournament. Holds Scottish FA Talent ID Level 1 Certification.",
        "certification": "IKFL1B240506",
        "featured": True,
    },
    {
        "name": "Zohaib Saigal",
        "slug": "zohaib-saigal",
        "photo": "Zohaib.jpeg",
        "city": "Kolkata",
        "state": "West Bengal",
        "age_date_of_birth": "22 Years (13/11/2003)",
        "languages": "English, Hindi",
        "willingness_to_travel": "Yes",
        "phone": "9123817018",
        "email": "zohaibsaigal@gmail.com",
        "experience": "1 year",
        "level1_completion_date": "12/12/2025 (IKF-CFSA-L1-B2509)",
        "level2_completion_date": "12/04/2026 (IKF-CFSA-L1-B2509)",
        "types": "Video",
        "competitions": "",
        "age_groups": "U15, U17",
        "regions": "West Bengal",
        "players_assessed": "500+",
        "shortlisted": "",
        "events": "",
        "strengths": "Tactical observation, positional scouting, player evaluation, match scouting (live + video), report writing and grading, Excel/Sheets/video tools.",
        "playing": "East Bengal U17s. Right back.",
        "achievements": "",
        "certification": "IKF-CFSA-L1-B2509",
        "featured": False,
    },
    {
        "name": "Nitin Singh",
        "slug": "nitin-singh",
        "photo": "Nitin.jpeg",
        "city": "Mumbai",
        "state": "Maharashtra",
        "age_date_of_birth": "35 Years (07/04/1991)",
        "languages": "Hindi, English",
        "willingness_to_travel": "Travel on assignments",
        "phone": "9892694708",
        "email": "cadetwzu@gmail.com",
        "experience": "3 years",
        "level1_completion_date": "18/08/2025 (IKF1B250705)",
        "level2_completion_date": "29/02/2026 (IKF1B250705)",
        "types": "Live match, grassroots",
        "competitions": "IKF National Finals",
        "age_groups": "U13, U15, U17",
        "regions": "Maharashtra, Goa, Gujarat",
        "players_assessed": "1000+",
        "shortlisted": "20",
        "events": "CIFA, West Zone United FC",
        "strengths": "Positional scouting, youth scouting and tactical observation, player evaluation, positional analysis, match scouting (live + video), report writing and grading.",
        "playing": "PDP Club, WZU FC. District / state level right back, centre back and right winger with 20 years active experience.",
        "achievements": "Players identified who progressed to higher trials. Recognised by clubs/academies/mentors. High accuracy in player grading.",
        "certification": "IKF1B250705",
        "featured": False,
    },
]


def get_scout_profile(slug):
    return next((profile for profile in SCOUT_PROFILES if profile["slug"] == slug), None)
